### ISSUE TITLE
2.0.0 Roadmap

### ISSUE THREAD

**Issue by jembezmamy** [nibynic/ember-form-builder#10]
Ember Form Builder became somewhat chaotic and inconsistent, so we're planning to reorganize it a bit and partially loose backward compatibility. This will become version 2.0.0.

- [ ] rename `simple-input`, `simple-label` and `simple-submit` to `form-builder/input`, `form-builder/label`, `form-builder/submit`
- [ ] remove `labelTranslation`, `hintTranslation`, `placeholderTranslation` from `form-builder/input` and `translation` from `form-builder/submit` - it serves no purpose since translation addons allow translating in template via helpers
- [ ] implement input layouts to allow easy customisation
- [ ] then remove `inlineLabel` in `form-builder/input` and replace it with an inline label layout
- [ ] remove `action()` and `submitFailed()` from `form-builder` and replace it with `didSubmit()` that expects a promise
- [ ] disable inputs while saving

**Comment by jembezmamy** [comment]
Moved each task into a separate issue
